[server]
headless = true

[theme]
primaryColor = "#1DA1F2"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1a2e"
textColor = "#fafafa"
font = "sans serif"

[browser]
gatherUsageStats = false
